name: Talos Insight
favicon: null
layout_spectrum: 0.89356
typography_spectrum: 0.57703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181717'
    - '#ffffff'
    - '#454545'
    - '#6d7174'
    - '#b3b6b9'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
