name: Talos Insight
favicon: null
layout_spectrum: 0.89356
typography_spectrum: 0.57703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e9d9d7'
    - '#a8a5ab'
    - '#7e818e'
    - '#54525b'
  brandStrength: 0.5060925602447242
  lightness: 0.8382833872456104
  saturation: 0.8870953151490539
  rhythmicContrast: 0.9372193175368011
purpose: []
